In [43]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np

In [44]:
X = [[2,4],[4,5],[8,4],[5,-2],[5,-6],[9,-5]]
y = [-1,-1,-1,1,1,1]

In [45]:
l = SVC(C=1e5,kernel="linear")

In [46]:
l.fit(X,y)

SVC(C=100000.0, kernel='linear')

In [47]:
print("w = ",l.coef_)
print("b = ",l.intercept_)
print("indices of support vectors = ",l.support_)
print("Support vectors = ",l.support_vectors_)
print("Number of support vectors = ",l.n_support_)
print("coefiecient of support vectors =",np.abs(l.dual_coef_))

w =  [[ 8.32667268e-17 -3.33226667e-01]]
b =  [0.33312]
indices of support vectors =  [0 2 3]
Support vectors =  [[ 2.  4.]
 [ 8.  4.]
 [ 5. -2.]]
Number of support vectors =  [2 1]
coefiecient of support vectors = [[0.02776889 0.02776889 0.05553778]]


In [48]:
import pandas as pd
data=pd.read_csv("glass.csv")
data.head()


Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [70]:
x=data.drop("Type",axis=1)
y=data.Type


In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
linear = svm.SVC(kernel="linear")
linear.fit(x_train,y_train)
print(linear.support_vectors_)
print(linear.n_support_)
y_pred = linear.predict(x_test)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [7.10000e+01 1.51574e+00 1.48600e+01 3.67000e+00 1.74000e+00 7.18700e+01
  1.60000e-01 7.36000e+00 0.00000e+00 1.20000e-01]
 [7.40000e+01 1.51631e+00 1.33400e+01 3.57000e+00 1.57000e+00 7.28700e+01
  6.10000e-01 7.89000e+00 0.00000e+00 0.00000e+00]
 [1.60000e+02 1.51796e+00 1.35000e+01 3.36000e+00 1.63000e+00 7.19400e+01
  5.70000e-01 8.81000e+00 0.00000e+00 9.00000e-02]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]
 [1.75000e+02 1.52058e+00 1.28500e+01 1.61000e+00 2.17000e+00 7.21800e+01
  7.60000e-01 9.70000e+00 2.40000e-01 5.10000e-01]


In [84]:
from sklearn.metrics import accuracy_score
print("Accuracy:\n",accuracy_score(y_test,y_pred))
from sklearn.metrics import confusion_matrix
print("Confusion matrix:\n",confusion_matrix(y_test,y_pred))
from sklearn.metrics import classification_report
print("Classification report:\n",classification_report(y_test,y_pred))

Accuracy:
 1.0
Confusion matrix:
 [[20  0  0  0  0  0]
 [ 0 21  0  0  0  0]
 [ 0  0  8  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0 10]]
Classification report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        20
           2       1.00      1.00      1.00        21
           3       1.00      1.00      1.00         8
           5       1.00      1.00      1.00         4
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00        10

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



In [88]:
model1 = SVC(kernel="sigmoid")
model2 = SVC(kernel="poly")
model3 = SVC(kernel="rbf")

In [90]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [92]:
y_pred1 = model1.predict(x_test)
y_pred2 = model2.predict(x_test)
y_pred3 = model3.predict(x_test)

In [102]:
print("Accuracy\n")
print("prediction by model1 : ",accuracy_score(y_test,y_pred1))
print("prediction by model2 : ",accuracy_score(y_test,y_pred2))
print("prediction by model3 : ",accuracy_score(y_test,y_pred3))

Accuracy

prediction by model1 :  0.5692307692307692
prediction by model2 :  0.9384615384615385
prediction by model3 :  0.8153846153846154


In [101]:
print("Confusion matrix\n")
print("prediction by model1 : \n",confusion_matrix(y_test,y_pred1))
print("prediction by model2 : \n",confusion_matrix(y_test,y_pred2))
print("prediction by model3 : \n",confusion_matrix(y_test,y_pred3))

Confusion matrix

prediction by model1 : 
 [[16  4  0  0  0  0]
 [ 0 21  0  0  0  0]
 [ 0  8  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0 10  0  0  0  0]]
prediction by model2 : 
 [[20  0  0  0  0  0]
 [ 1 19  1  0  0  0]
 [ 0  0  6  2  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0 10]]
prediction by model3 : 
 [[19  1  0  0  0  0]
 [ 0 21  0  0  0  0]
 [ 0  6  0  2  0  0]
 [ 0  0  0  3  0  1]
 [ 0  0  0  0  0  2]
 [ 0  0  0  0  0 10]]


In [100]:
print("Classification report\n")
print("prediction by model1 : \n",classification_report(y_test,y_pred1))
print("prediction by model2 : \n",classification_report(y_test,y_pred2))
print("prediction by model3 : \n",classification_report(y_test,y_pred3))

Classification report

prediction by model1 : 
               precision    recall  f1-score   support

           1       1.00      0.80      0.89        20
           2       0.43      1.00      0.60        21
           3       0.00      0.00      0.00         8
           5       0.00      0.00      0.00         4
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00        10

    accuracy                           0.57        65
   macro avg       0.24      0.30      0.25        65
weighted avg       0.45      0.57      0.47        65

prediction by model2 : 
               precision    recall  f1-score   support

           1       0.95      1.00      0.98        20
           2       1.00      0.90      0.95        21
           3       0.86      0.75      0.80         8
           5       0.67      1.00      0.80         4
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00        10

    

C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\